// คลังคำภาษาไทยสำหรับเกมสายลับ — คำนามทั่วไปที่ใช้ใบ้ง่าย
// 458 คำ ไม่ซ้ำ: สัตว์ อาหาร สถานที่ ของใช้ ธรรมชาติ อาชีพ ฯลฯ
// English glosses sit under each Thai word so lookalikes like ชา / ขา stay clear.

export const WORD_PAIRS = [
  // สัตว์
  ["ช้าง", "Elephant"],
  ["เสือ", "Tiger"],
  ["สิงโต", "Lion"],
  ["หมี", "Bear"],
  ["หมา", "Dog"],
  ["แมว", "Cat"],
  ["ม้า", "Horse"],
  ["วัว", "Cow"],
  ["ควาย", "Buffalo"],
  ["หมู", "Pig"],
  ["ไก่", "Chicken"],
  ["เป็ด", "Duck"],
  ["นก", "Bird"],
  ["ปลา", "Fish"],
  ["ปู", "Crab"],
  ["กุ้ง", "Shrimp"],
  ["หอย", "Shell"],
  ["งู", "Snake"],
  ["จระเข้", "Crocodile"],
  ["เต่า", "Turtle"],
  ["กบ", "Frog"],
  ["ผีเสื้อ", "Butterfly"],
  ["แมลง", "Insect"],
  ["ผึ้ง", "Bee"],
  ["มด", "Ant"],
  ["ยุง", "Mosquito"],
  ["แมงมุม", "Spider"],
  ["ลิง", "Monkey"],
  ["กระต่าย", "Rabbit"],
  ["หนู", "Rat"],
  ["ยีราฟ", "Giraffe"],
  ["ม้าลาย", "Zebra"],
  ["แพนด้า", "Panda"],
  ["โลมา", "Dolphin"],
  ["ฉลาม", "Shark"],
  ["ปลาวาฬ", "Whale"],
  ["นกฮูก", "Owl"],
  ["นกแก้ว", "Parrot"],
  ["เหยี่ยว", "Hawk"],
  ["อินทรี", "Eagle"],
  ["กวาง", "Deer"],
  ["แกะ", "Sheep"],
  ["แพะ", "Goat"],
  ["อูฐ", "Camel"],
  ["จิงโจ้", "Kangaroo"],
  ["เพนกวิน", "Penguin"],
  ["หงส์", "Swan"],
  ["แมงป่อง", "Scorpion"],
  ["ตะกวด", "Monitor Lizard"],
  ["ค้างคาว", "Bat"],

  // อาหาร / ผลไม้ / เครื่องดื่ม
  ["ข้าว", "Rice"],
  ["ก๋วยเตี๋ยว", "Noodles"],
  ["ผัดไทย", "Pad Thai"],
  ["ต้มยำ", "Tom Yum"],
  ["แกง", "Curry"],
  ["ส้มตำ", "Papaya Salad"],
  ["ไก่ย่าง", "Grilled Chicken"],
  ["ข้าวเหนียว", "Sticky Rice"],
  ["ข้าวผัด", "Fried Rice"],
  ["หมูกรอบ", "Crispy Pork"],
  ["ขนมปัง", "Bread"],
  ["เค้ก", "Cake"],
  ["ไอศกรีม", "Ice Cream"],
  ["ช็อกโกแลต", "Chocolate"],
  ["ลูกอม", "Candy"],
  ["คุกกี้", "Cookie"],
  ["โดนัท", "Donut"],
  ["พิซซ่า", "Pizza"],
  ["เบอร์เกอร์", "Burger"],
  ["ซูชิ", "Sushi"],
  ["ไข่", "Egg"],
  ["นม", "Milk"],
  ["เนย", "Butter"],
  ["ชีส", "Cheese"],
  ["น้ำตาล", "Sugar"],
  ["เกลือ", "Salt"],
  ["พริก", "Chili"],
  ["กระเทียม", "Garlic"],
  ["หอม", "Onion"],
  ["ขิง", "Ginger"],
  ["มะนาว", "Lime"],
  ["มะม่วง", "Mango"],
  ["กล้วย", "Banana"],
  ["ส้ม", "Orange"],
  ["แอปเปิ้ล", "Apple"],
  ["องุ่น", "Grape"],
  ["สับปะรด", "Pineapple"],
  ["แตงโม", "Watermelon"],
  ["ทุเรียน", "Durian"],
  ["มังคุด", "Mangosteen"],
  ["มะพร้าว", "Coconut"],
  ["สตรอว์เบอร์รี", "Strawberry"],
  ["ลิ้นจี่", "Lychee"],
  ["ลำไย", "Longan"],
  ["เงาะ", "Rambutan"],
  ["ฝรั่ง", "Guava"],
  ["ชมพู่", "Rose Apple"],
  ["แก้วมังกร", "Dragonfruit"],
  ["กาแฟ", "Coffee"],
  ["ชา", "Tea"],
  ["น้ำ", "Water"],
  ["น้ำแข็ง", "Ice"],
  ["เบียร์", "Beer"],
  ["ไวน์", "Wine"],
  ["น้ำผลไม้", "Juice"],
  ["โซดา", "Soda"],
  ["นมเปรี้ยว", "Yogurt"],
  ["ซอส", "Sauce"],
  ["น้ำปลา", "Fish Sauce"],
  ["น้ำจิ้ม", "Dipping Sauce"],

  // สถานที่
  ["โรงเรียน", "School"],
  ["มหาวิทยาลัย", "University"],
  ["โรงพยาบาล", "Hospital"],
  ["ธนาคาร", "Bank"],
  ["ตลาด", "Market"],
  ["ห้าง", "Mall"],
  ["ร้านอาหาร", "Restaurant"],
  ["โรงแรม", "Hotel"],
  ["สนามบิน", "Airport"],
  ["สถานี", "Station"],
  ["วัด", "Temple"],
  ["โบสถ์", "Church"],
  ["พิพิธภัณฑ์", "Museum"],
  ["สวนสัตว์", "Zoo"],
  ["สวนสนุก", "Theme Park"],
  ["สวนสาธารณะ", "Park"],
  ["ชายหาด", "Beach"],
  ["ภูเขา", "Mountain"],
  ["ทะเล", "Sea"],
  ["แม่น้ำ", "River"],
  ["ทะเลสาบ", "Lake"],
  ["น้ำตก", "Waterfall"],
  ["ป่า", "Forest"],
  ["ทะเลทราย", "Desert"],
  ["เกาะ", "Island"],
  ["ถ้ำ", "Cave"],
  ["หมู่บ้าน", "Village"],
  ["เมือง", "City"],
  ["ประเทศ", "Country"],
  ["จังหวัด", "Province"],
  ["กรุงเทพ", "Bangkok"],
  ["เชียงใหม่", "Chiang Mai"],
  ["ภูเก็ต", "Phuket"],
  ["พัทยา", "Pattaya"],
  ["อยุธยา", "Ayutthaya"],
  ["ญี่ปุ่น", "Japan"],
  ["จีน", "China"],
  ["เกาหลี", "Korea"],
  ["อเมริกา", "America"],
  ["ฝรั่งเศส", "France"],
  ["ปารีส", "Paris"],
  ["ลอนดอน", "London"],
  ["โตเกียว", "Tokyo"],
  ["นิวยอร์ก", "New York"],
  ["สิงคโปร์", "Singapore"],
  ["สนามบอล", "Soccer Field"],
  ["สนามกอล์ฟ", "Golf Course"],
  ["ยิม", "Gym"],
  ["สปา", "Spa"],
  ["ห้องสมุด", "Library"],

  // ของใช้ในบ้าน
  ["โต๊ะ", "Table"],
  ["เก้าอี้", "Chair"],
  ["เตียง", "Bed"],
  ["ตู้", "Cabinet"],
  ["โซฟา", "Sofa"],
  ["กระจก", "Mirror"],
  ["หน้าต่าง", "Window"],
  ["ประตู", "Door"],
  ["พรม", "Rug"],
  ["ม่าน", "Curtain"],
  ["หมอน", "Pillow"],
  ["ผ้าห่ม", "Blanket"],
  ["จาน", "Plate"],
  ["ชาม", "Bowl"],
  ["ช้อน", "Spoon"],
  ["ส้อม", "Fork"],
  ["มีด", "Knife"],
  ["ตะเกียบ", "Chopsticks"],
  ["แก้ว", "Glass"],
  ["ขวด", "Bottle"],
  ["หม้อ", "Pot"],
  ["กระทะ", "Pan"],
  ["เตา", "Stove"],
  ["ตู้เย็น", "Fridge"],
  ["เตาอบ", "Oven"],
  ["ไมโครเวฟ", "Microwave"],
  ["เครื่องซักผ้า", "Washer"],
  ["พัดลม", "Fan"],
  ["แอร์", "Air-Con"],
  ["ทีวี", "TV"],
  ["นาฬิกา", "Clock"],
  ["โคมไฟ", "Lamp"],
  ["เทียน", "Candle"],
  ["สบู่", "Soap"],
  ["ยาสีฟัน", "Toothpaste"],
  ["แปรงสีฟัน", "Toothbrush"],
  ["ผ้าเช็ดตัว", "Towel"],
  ["หวี", "Comb"],
  ["กระเป๋า", "Bag"],
  ["ร่ม", "Umbrella"],

  // เทคโนโลยี
  ["คอมพิวเตอร์", "Computer"],
  ["โน้ตบุ๊ก", "Laptop"],
  ["มือถือ", "Phone"],
  ["แท็บเล็ต", "Tablet"],
  ["กล้อง", "Camera"],
  ["หูฟัง", "Headphones"],
  ["ลำโพง", "Speaker"],
  ["คีย์บอร์ด", "Keyboard"],
  ["เมาส์", "Mouse"],
  ["จอ", "Screen"],
  ["อินเทอร์เน็ต", "Internet"],
  ["เว็บไซต์", "Website"],
  ["อีเมล", "Email"],
  ["รหัสผ่าน", "Password"],
  ["หุ่นยนต์", "Robot"],
  ["โดรน", "Drone"],
  ["ดาวเทียม", "Satellite"],
  ["จรวด", "Rocket"],
  ["ปัญญาประดิษฐ์", "AI"],
  ["เกม", "Game"],

  // ยานพาหนะ
  ["รถยนต์", "Car"],
  ["มอเตอร์ไซค์", "Motorcycle"],
  ["จักรยาน", "Bicycle"],
  ["รถบัส", "Bus"],
  ["รถไฟ", "Train"],
  ["รถตู้", "Van"],
  ["รถกระบะ", "Pickup"],
  ["แท็กซี่", "Taxi"],
  ["ตุ๊กตุ๊ก", "Tuk-Tuk"],
  ["สามล้อ", "Tricycle"],
  ["เครื่องบิน", "Airplane"],
  ["เรือ", "Boat"],
  ["เรือใบ", "Sailboat"],
  ["เรือดำน้ำ", "Submarine"],
  ["เฮลิคอปเตอร์", "Helicopter"],
  ["รถถัง", "Tank"],
  ["รถบรรทุก", "Truck"],
  ["เกวียน", "Cart"],
  ["สกู๊ตเตอร์", "Scooter"],
  ["สเก็ตบอร์ด", "Skateboard"],

  // ร่างกาย
  ["หัว", "Head"],
  ["ผม", "Hair"],
  ["หน้า", "Face"],
  ["ตา", "Eye"],
  ["หู", "Ear"],
  ["จมูก", "Nose"],
  ["ปาก", "Mouth"],
  ["ฟัน", "Tooth"],
  ["ลิ้น", "Tongue"],
  ["คอ", "Neck"],
  ["มือ", "Hand"],
  ["แขน", "Arm"],
  ["นิ้ว", "Finger"],
  ["เล็บ", "Nail"],
  ["ขา", "Leg"],
  ["เท้า", "Foot"],
  ["หัวเข่า", "Knee"],
  ["หลัง", "Back"],
  ["ท้อง", "Belly"],
  ["หัวใจ", "Heart"],

  // ธรรมชาติ / สภาพอากาศ
  ["พระอาทิตย์", "Sun"],
  ["พระจันทร์", "Moon"],
  ["ดาว", "Star"],
  ["เมฆ", "Cloud"],
  ["ฝน", "Rain"],
  ["ฟ้าแลบ", "Lightning"],
  ["ฟ้าร้อง", "Thunder"],
  ["หิมะ", "Snow"],
  ["ลม", "Wind"],
  ["พายุ", "Storm"],
  ["รุ้ง", "Rainbow"],
  ["ไฟ", "Fire"],
  ["ดิน", "Soil"],
  ["หิน", "Rock"],
  ["ทราย", "Sand"],
  ["ต้นไม้", "Tree"],
  ["ดอกไม้", "Flower"],
  ["ใบไม้", "Leaf"],
  ["หญ้า", "Grass"],
  ["ดอกกุหลาบ", "Rose"],
  ["ดอกบัว", "Lotus"],
  ["กล้วยไม้", "Orchid"],
  ["ดอกทานตะวัน", "Sunflower"],
  ["มะพร้าวน้ำหอม", "Fragrant Coconut"],
  ["ไผ่", "Bamboo"],
  ["สน", "Pine"],
  ["มะฮอกกานี", "Mahogany"],
  ["เห็ด", "Mushroom"],
  ["สาหร่าย", "Seaweed"],

  // อาชีพ / บุคคล
  ["หมอ", "Doctor"],
  ["พยาบาล", "Nurse"],
  ["ครู", "Teacher"],
  ["ตำรวจ", "Police"],
  ["ทหาร", "Soldier"],
  ["นักดับเพลิง", "Firefighter"],
  ["นักบิน", "Pilot"],
  ["พ่อครัว", "Chef"],
  ["นักร้อง", "Singer"],
  ["นักแสดง", "Actor"],
  ["นักกีฬา", "Athlete"],
  ["นักวิทยาศาสตร์", "Scientist"],
  ["นักเขียน", "Writer"],
  ["ศิลปิน", "Artist"],
  ["ชาวนา", "Farmer"],
  ["ช่างไม้", "Carpenter"],
  ["ช่างยนต์", "Mechanic"],
  ["โปรแกรมเมอร์", "Programmer"],
  ["วิศวกร", "Engineer"],
  ["ทนาย", "Lawyer"],
  ["ประธานาธิบดี", "President"],
  ["นายก", "Premier"],
  ["ราชา", "King"],
  ["ราชินี", "Queen"],
  ["เจ้าชาย", "Prince"],
  ["เจ้าหญิง", "Princess"],
  ["อัศวิน", "Knight"],
  ["โจรสลัด", "Pirate"],
  ["นินจา", "Ninja"],
  ["ซามูไร", "Samurai"],
  ["พ่อ", "Father"],
  ["แม่", "Mother"],
  ["พี่", "Elder Sib"],
  ["น้อง", "Younger Sib"],
  ["ลูก", "Child"],
  ["เพื่อน", "Friend"],
  ["แฟน", "Partner"],
  ["คุณปู่", "Grandpa"],
  ["คุณย่า", "Grandma"],
  ["เด็ก", "Kid"],

  // กีฬา / งานอดิเรก
  ["ฟุตบอล", "Soccer"],
  ["บาสเกตบอล", "Basketball"],
  ["เทนนิส", "Tennis"],
  ["แบดมินตัน", "Badminton"],
  ["ว่ายน้ำ", "Swimming"],
  ["วิ่ง", "Running"],
  ["โยคะ", "Yoga"],
  ["มวย", "Boxing"],
  ["กอล์ฟ", "Golf"],
  ["ปิงปอง", "Ping-Pong"],
  ["หมากรุก", "Chess"],
  ["ไพ่", "Cards"],
  ["การ์ด", "Card"],
  ["หนังสือ", "Book"],
  ["นิยาย", "Novel"],
  ["หนัง", "Movie"],
  ["ละคร", "Drama"],
  ["เพลง", "Song"],
  ["กีตาร์", "Guitar"],
  ["เปียโน", "Piano"],
  ["กลอง", "Drum"],
  ["ไวโอลิน", "Violin"],
  ["ระบำ", "Dance"],
  ["เต้น", "Dancing"],
  ["วาดรูป", "Drawing"],
  ["ถ่ายรูป", "Photo"],
  ["ตกปลา", "Fishing"],
  ["แคมป์ปิ้ง", "Camping"],
  ["ปีนเขา", "Climbing"],
  ["ดำน้ำ", "Diving"],

  // นามธรรม / แนวคิด
  ["ความรัก", "Love"],
  ["ความสุข", "Happiness"],
  ["ความเศร้า", "Sadness"],
  ["ความโกรธ", "Anger"],
  ["ความกลัว", "Fear"],
  ["ความฝัน", "Dream"],
  ["ความหวัง", "Hope"],
  ["ความจริง", "Truth"],
  ["ความลับ", "Secret"],
  ["อิสรภาพ", "Freedom"],
  ["เวลา", "Time"],
  ["อดีต", "Past"],
  ["ปัจจุบัน", "Present"],
  ["อนาคต", "Future"],
  ["ชีวิต", "Life"],
  ["ความตาย", "Death"],
  ["โชค", "Luck"],
  ["ดวง", "Fortune"],
  ["เงิน", "Money"],
  ["ทอง", "Gold"],
  ["เพชร", "Diamond"],
  ["มงกุฎ", "Crown"],
  ["ธง", "Flag"],
  ["แผนที่", "Map"],
  ["เข็มทิศ", "Compass"],
  ["กุญแจ", "Key"],
  ["ล็อก", "Lock"],
  ["สมบัติ", "Treasure"],
  ["หีบ", "Chest"],

  // เครื่องแต่งกาย
  ["เสื้อ", "Shirt"],
  ["กางเกง", "Pants"],
  ["กระโปรง", "Skirt"],
  ["ชุด", "Outfit"],
  ["รองเท้า", "Shoes"],
  ["ถุงเท้า", "Socks"],
  ["หมวก", "Hat"],
  ["แว่นตา", "Glasses"],
  ["นาฬิกาข้อมือ", "Watch"],
  ["สร้อย", "Necklace"],
  ["แหวน", "Ring"],
  ["ต่างหู", "Earring"],
  ["เข็มขัด", "Belt"],
  ["กระเป๋าถือ", "Handbag"],
  ["เน็คไท", "Necktie"],
  ["ผ้าพันคอ", "Scarf"],
  ["ถุงมือ", "Gloves"],
  ["บิกินี่", "Bikini"],
  ["ชุดว่ายน้ำ", "Swimsuit"],
  ["ชุดนอน", "Pajamas"],

  // อื่น ๆ
  ["ปืน", "Gun"],
  ["ดาบ", "Sword"],
  ["ธนู", "Bow"],
  ["ระเบิด", "Bomb"],
  ["โล่", "Shield"],
  ["เกราะ", "Armor"],
  ["ปราสาท", "Castle"],
  ["ปิรามิด", "Pyramid"],
  ["สะพาน", "Bridge"],
  ["ตึก", "Building"],
  ["หอคอย", "Tower"],
  ["กำแพง", "Wall"],
  ["บันได", "Stairs"],
  ["ลิฟต์", "Elevator"],
  ["เสา", "Pillar"],
  ["หลังคา", "Roof"],
  ["พื้น", "Floor"],
  ["ปล่องไฟ", "Chimney"],
  ["เตาผิง", "Fireplace"],
  ["อ่างน้ำ", "Bathtub"],
  ["บอลลูน", "Air Balloon"],
  ["ว่าว", "Kite"],
  ["ของเล่น", "Toy"],
  ["ตุ๊กตา", "Doll"],
  ["ลูกโป่ง", "Balloon"],
  ["ลูกบอล", "Ball"],
  ["ของขวัญ", "Gift"],
  ["กล่อง", "Box"],
  ["ถุง", "Sack"],
  ["ตะกร้า", "Basket"],
  ["ผี", "Ghost"],
  ["มังกร", "Dragon"],
  ["ยูนิคอร์น", "Unicorn"],
  ["นางฟ้า", "Fairy"],
  ["แม่มด", "Witch"],
  ["เวทมนตร์", "Magic"],
  ["ไม้กายสิทธิ์", "Wand"],
  ["คาถา", "Spell"],
  ["คำสาป", "Curse"],
  ["อมตะ", "Immortal"],
  ["ยา", "Medicine"],
  ["วัคซีน", "Vaccine"],
  ["เชื้อโรค", "Germ"],
  ["ไวรัส", "Virus"],
  ["ดีเอ็นเอ", "DNA"],
  ["เซลล์", "Cell"],
  ["สมอง", "Brain"],
  ["กระดูก", "Bone"],
  ["เลือด", "Blood"],
  ["ออกซิเจน", "Oxygen"],

];

export const THAI_WORDS = WORD_PAIRS.map(([th]) => th);

export const THAI_TO_EN = Object.fromEntries(WORD_PAIRS);

export function englishFor(thai) {
  return THAI_TO_EN[thai] || '';
}

export function spokenLabel(thai) {
  const en = englishFor(thai);
  return en ? thai + ' (' + en + ')' : thai;
}
